/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.School_app.AuthSystem;

import com.mycompany.School_app.StatusSystem.Status;

import java.util.Date;

/**
 *
 * @author mohamed waleed
 */
public class StudentCreatorUI extends javax.swing.JFrame {
    private String name;
    private String email;
    private String password;
    /**
     * Creates new form StudentCreatorUI
     */
    public StudentCreatorUI() {
        initComponents();
    }

    public StudentCreatorUI(String name, String email, String password) {
        initComponents();
        custominit(name,email,password);
    }

    private void custominit(String name, String email, String password) {
        setVisible(true);
        this.name=name;
        this.email=email;
        this.password=password;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Student_ParentName_Label = new javax.swing.JLabel();
        Student_ParentName_txt = new javax.swing.JTextField();
        Student_DOB_Label = new javax.swing.JLabel();
        Student_DOB_Chooser = new com.toedter.calendar.JDateChooser();
        Student_Gender_Label = new javax.swing.JLabel();
        Student_Gender_Selector = new javax.swing.JComboBox<>();
        Student_MobileNo_Label = new javax.swing.JLabel();
        Student_MobileNo_txt = new javax.swing.JTextField();
        Student_Address_Label = new javax.swing.JLabel();
        Student_Address_txt = new javax.swing.JTextField();
        Student_Section_Label = new javax.swing.JLabel();
        Student_Section_txt = new javax.swing.JTextField();
        Status_Label = new javax.swing.JLabel();
        Cancel_btn = new javax.swing.JButton();
        Create_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Creator");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        Student_ParentName_Label.setText("Parent Name");

        Student_DOB_Label.setText("Date Of Birth");

        Student_Gender_Label.setText("Gender");

        Student_Gender_Selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        Student_MobileNo_Label.setText("Mobile Number");

        Student_MobileNo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Student_MobileNo_txtKeyTyped(evt);
            }
        });

        Student_Address_Label.setText("Address");

        Student_Section_Label.setText("Section");

        Student_Section_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Student_Section_txtKeyTyped(evt);
            }
        });

        Status_Label.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        Cancel_btn.setText("Cancel");
        Cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_btnActionPerformed(evt);
            }
        });

        Create_btn.setText("Create");
        Create_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Student_ParentName_Label)
                            .addComponent(Student_DOB_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Student_ParentName_txt)
                            .addComponent(Student_DOB_Chooser, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Status_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cancel_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Create_btn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Student_MobileNo_Label)
                            .addComponent(Student_Address_Label)
                            .addComponent(Student_Section_Label)
                            .addComponent(Student_Gender_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Student_Gender_Selector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Student_Section_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(Student_Address_txt)
                            .addComponent(Student_MobileNo_txt))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Student_ParentName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Student_ParentName_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Student_DOB_Chooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Student_DOB_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Student_Gender_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Student_Gender_Selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Student_MobileNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Student_MobileNo_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Student_Address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Student_Address_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Student_Section_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Student_Section_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Create_btn)
                            .addComponent(Cancel_btn)))
                    .addComponent(Status_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Create_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_btnActionPerformed
        // TODO add your handling code here:
        String parentName = Student_ParentName_txt.getText();
        Date DOB = Student_DOB_Chooser.getDate();
        String gender = Student_Gender_Selector.getSelectedItem().toString();
        String mobileNo = Student_MobileNo_txt.getText();
        String address = Student_Address_txt.getText();
        String section = Student_Section_txt.getText();

        AuthManager.RegisterStudent(name,email,password,parentName,DOB,gender,mobileNo,address,section);

        Status status = AuthManager.getStatus();
        Status_Label.setText(status.getstatusMessage());

        switch (status.getErrorCode()) {
            case 1->{Student_ParentName_txt.requestFocus();}
            case 2->{Student_DOB_Chooser.requestFocus();}
            case 3->{Student_Gender_Selector.requestFocus();}
            case 4->{Student_MobileNo_txt.requestFocus();}
            case 5->{Student_Address_txt.requestFocus();}
            case 6->{Student_Section_txt.requestFocus();}
        }
    }//GEN-LAST:event_Create_btnActionPerformed

    private void Cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AuthManagerUI();
    }//GEN-LAST:event_Cancel_btnActionPerformed

    private void Student_MobileNo_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Student_MobileNo_txtKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Student_MobileNo_txtKeyTyped

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    private void Student_Section_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Student_Section_txtKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isLetter(c)) {
            evt.consume();
        }
        if (Student_Section_txt.getText().length() >= 1) {
            evt.consume(); // ignore extra input
        }
    }//GEN-LAST:event_Student_Section_txtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentCreatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentCreatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentCreatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentCreatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentCreatorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel_btn;
    private javax.swing.JButton Create_btn;
    private javax.swing.JLabel Status_Label;
    private javax.swing.JLabel Student_Address_Label;
    private javax.swing.JTextField Student_Address_txt;
    private com.toedter.calendar.JDateChooser Student_DOB_Chooser;
    private javax.swing.JLabel Student_DOB_Label;
    private javax.swing.JLabel Student_Gender_Label;
    private javax.swing.JComboBox<String> Student_Gender_Selector;
    private javax.swing.JLabel Student_MobileNo_Label;
    private javax.swing.JTextField Student_MobileNo_txt;
    private javax.swing.JLabel Student_ParentName_Label;
    private javax.swing.JTextField Student_ParentName_txt;
    private javax.swing.JLabel Student_Section_Label;
    private javax.swing.JTextField Student_Section_txt;
    // End of variables declaration//GEN-END:variables
}
