/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.School_app.MainApp;

import com.mycompany.School_app.LibrarySystem.Book;
import com.mycompany.School_app.LibrarySystem.Librarian;
import com.mycompany.School_app.StatusSystem.Status;
import com.mycompany.School_app.ThemeManger.ThemeMangerUI;
import com.mycompany.School_app.User.Student;
import com.mycompany.School_app.User.Teacher;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author mohamed waleed
 */
public class LibrarianAppUI extends javax.swing.JFrame {
    Librarian user;
    Book SelectedBook;
    /**
     * Creates new form LibrarianAppUI
     */
    public LibrarianAppUI() {
        initComponents();
    }

    public LibrarianAppUI(Librarian user) {
        initComponents();
        custominit(user);
    }

    public void custominit(Librarian user){
        ArrayList<String> Experiencelvls = new ArrayList<>();
        for (int i = 1; i <= 10; i++) {
            if (i == 1) {Experiencelvls.add(i + " Year"); continue;}
            Experiencelvls.add(i + " Years");
        }
        Librarian_Exp_Selector.setModel(new javax.swing.DefaultComboBoxModel<>(Experiencelvls.stream().toArray(String[]::new)));
        setLocationRelativeTo(null);
        setVisible(true);
        this.user = user;
        ReloadProfileFields();
        refreshBooksTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AppPanel = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Book_btn = new javax.swing.JButton();
        Profile_btn = new javax.swing.JButton();
        Logout_btn = new javax.swing.JButton();
        MainPanel = new javax.swing.JLayeredPane();
        Book_Panel = new javax.swing.JPanel();
        Book_Table_Scroll = new javax.swing.JScrollPane();
        Book_Table = new javax.swing.JTable();
        Book_Tabbed_Panel = new javax.swing.JTabbedPane();
        Book_Info_Tab = new javax.swing.JPanel();
        Book_ISBN_Label = new javax.swing.JLabel();
        Book_Name_Label = new javax.swing.JLabel();
        Book_Name_txt = new javax.swing.JTextField();
        Book_Save_btn = new javax.swing.JButton();
        Book_Clear_btn = new javax.swing.JButton();
        Book_Create_btn = new javax.swing.JButton();
        Book_Delete_btn = new javax.swing.JButton();
        Book_Reset_btn = new javax.swing.JButton();
        Book_ISBN_txt = new javax.swing.JTextField();
        Book_Author_txt = new javax.swing.JTextField();
        Book_Author_Label = new javax.swing.JLabel();
        Book_Status_Checkbox = new javax.swing.JCheckBox();
        Profile_Panel = new javax.swing.JPanel();
        Profile_Label = new javax.swing.JLabel();
        Reset_Profile_btn = new javax.swing.JButton();
        Delete_Acc_btn = new javax.swing.JButton();
        Librarian_ID_Label = new javax.swing.JLabel();
        Librarian_ID_txt = new javax.swing.JTextField();
        Librarian_Name_Label = new javax.swing.JLabel();
        Librarian_Name_txt = new javax.swing.JTextField();
        Librarian_Email_Label = new javax.swing.JLabel();
        Librarian_Email_txt = new javax.swing.JTextField();
        Librarian_Password_Label = new javax.swing.JLabel();
        Librarian_Password_txt = new javax.swing.JPasswordField();
        Status_Profile_Label = new javax.swing.JLabel();
        Save_Profile_btn = new javax.swing.JButton();
        Librarian_Exp_Label = new javax.swing.JLabel();
        Librarian_Exp_Selector = new javax.swing.JComboBox<>();
        App_MenuBar = new javax.swing.JMenuBar();
        File_Menu = new javax.swing.JMenu();
        View_Menu = new javax.swing.JMenu();
        Theme_Menu_Item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("School.ap(Librarian)");

        Header.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Book_btn.setText("Student");
        Book_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_btnActionPerformed(evt);
            }
        });

        Profile_btn.setText("Mohamed Waleed");
        Profile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_btnActionPerformed(evt);
            }
        });

        Logout_btn.setText("Logout");
        Logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Book_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Profile_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Logout_btn)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Profile_btn)
                    .addComponent(Logout_btn)
                    .addComponent(Book_btn))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        MainPanel.setLayout(new java.awt.CardLayout());

        Book_Panel.setToolTipText("");

        Book_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Name", "Author", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Book_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Book_TableMouseClicked(evt);
            }
        });
        Book_Table_Scroll.setViewportView(Book_Table);

        Book_ISBN_Label.setText("ISBN");

        Book_Name_Label.setText("Name");

        Book_Save_btn.setText("Save");
        Book_Save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_Save_btnActionPerformed(evt);
            }
        });

        Book_Clear_btn.setText("Clear");
        Book_Clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_Clear_btnActionPerformed(evt);
            }
        });

        Book_Create_btn.setText("Create");
        Book_Create_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_Create_btnActionPerformed(evt);
            }
        });

        Book_Delete_btn.setText("Delete");
        Book_Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_Delete_btnActionPerformed(evt);
            }
        });

        Book_Reset_btn.setText("Reset");
        Book_Reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_Reset_btnActionPerformed(evt);
            }
        });

        Book_ISBN_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_ISBN_txtActionPerformed(evt);
            }
        });

        Book_Author_Label.setText("Author");

        Book_Status_Checkbox.setText("Available");
        Book_Status_Checkbox.setEnabled(false);
        Book_Status_Checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_Status_CheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Book_Info_TabLayout = new javax.swing.GroupLayout(Book_Info_Tab);
        Book_Info_Tab.setLayout(Book_Info_TabLayout);
        Book_Info_TabLayout.setHorizontalGroup(
            Book_Info_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Book_Info_TabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Book_Info_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Book_Info_TabLayout.createSequentialGroup()
                        .addGroup(Book_Info_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Book_ISBN_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Book_Name_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16))
                    .addComponent(Book_Name_txt)
                    .addGroup(Book_Info_TabLayout.createSequentialGroup()
                        .addComponent(Book_Save_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Book_Clear_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(Book_Info_TabLayout.createSequentialGroup()
                        .addComponent(Book_Create_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Book_Reset_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Book_Info_TabLayout.createSequentialGroup()
                        .addComponent(Book_Delete_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(Book_ISBN_txt)
                    .addGroup(Book_Info_TabLayout.createSequentialGroup()
                        .addComponent(Book_Author_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addComponent(Book_Author_txt)
                    .addComponent(Book_Status_Checkbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        Book_Info_TabLayout.setVerticalGroup(
            Book_Info_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Book_Info_TabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Book_ISBN_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Book_ISBN_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Book_Name_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Book_Name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Book_Author_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Book_Author_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Book_Status_Checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286)
                .addGroup(Book_Info_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Book_Save_btn)
                    .addComponent(Book_Clear_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Book_Info_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Book_Create_btn)
                    .addComponent(Book_Reset_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Book_Delete_btn)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        Book_Tabbed_Panel.addTab("Info", Book_Info_Tab);

        javax.swing.GroupLayout Book_PanelLayout = new javax.swing.GroupLayout(Book_Panel);
        Book_Panel.setLayout(Book_PanelLayout);
        Book_PanelLayout.setHorizontalGroup(
            Book_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Book_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Book_Tabbed_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Book_Table_Scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                .addContainerGap())
        );
        Book_PanelLayout.setVerticalGroup(
            Book_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Book_Table_Scroll)
            .addGroup(Book_PanelLayout.createSequentialGroup()
                .addComponent(Book_Tabbed_Panel)
                .addContainerGap())
        );

        MainPanel.add(Book_Panel, "card2");

        Profile_Label.setText("Profile");

        Reset_Profile_btn.setText("Reset");
        Reset_Profile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_Profile_btnActionPerformed(evt);
            }
        });

        Delete_Acc_btn.setText("Delete Account");
        Delete_Acc_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_Acc_btnActionPerformed(evt);
            }
        });

        Librarian_ID_Label.setText("ID:");

        Librarian_ID_txt.setEditable(false);

        Librarian_Name_Label.setText("Name:");

        Librarian_Email_Label.setText("Email:");

        Librarian_Password_Label.setText("Password:");

        Status_Profile_Label.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        Save_Profile_btn.setText("Save");
        Save_Profile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_Profile_btnActionPerformed(evt);
            }
        });

        Librarian_Exp_Label.setText("Experience");

        Librarian_Exp_Selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Librarian_Exp_SelectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Profile_PanelLayout = new javax.swing.GroupLayout(Profile_Panel);
        Profile_Panel.setLayout(Profile_PanelLayout);
        Profile_PanelLayout.setHorizontalGroup(
            Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Profile_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Profile_PanelLayout.createSequentialGroup()
                        .addComponent(Status_Profile_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Save_Profile_btn))
                    .addGroup(Profile_PanelLayout.createSequentialGroup()
                        .addComponent(Profile_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Reset_Profile_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delete_Acc_btn))
                    .addGroup(Profile_PanelLayout.createSequentialGroup()
                        .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Profile_PanelLayout.createSequentialGroup()
                                .addComponent(Librarian_ID_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Librarian_ID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Librarian_Name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Profile_PanelLayout.createSequentialGroup()
                                .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Profile_PanelLayout.createSequentialGroup()
                                        .addComponent(Librarian_Exp_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Librarian_Exp_Selector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Profile_PanelLayout.createSequentialGroup()
                                        .addComponent(Librarian_Email_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Librarian_Email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Librarian_Password_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Librarian_Name_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                            .addComponent(Librarian_Password_txt))))
                .addContainerGap())
        );
        Profile_PanelLayout.setVerticalGroup(
            Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Profile_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Profile_Label)
                    .addComponent(Delete_Acc_btn)
                    .addComponent(Reset_Profile_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Librarian_ID_Label)
                    .addComponent(Librarian_ID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Librarian_Name_Label)
                    .addComponent(Librarian_Name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Librarian_Email_Label)
                    .addComponent(Librarian_Email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Librarian_Password_Label)
                    .addComponent(Librarian_Password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Profile_PanelLayout.createSequentialGroup()
                        .addGap(0, 526, Short.MAX_VALUE)
                        .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Status_Profile_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Save_Profile_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(Profile_PanelLayout.createSequentialGroup()
                        .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Librarian_Exp_Selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Librarian_Exp_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        MainPanel.add(Profile_Panel, "card4");

        javax.swing.GroupLayout AppPanelLayout = new javax.swing.GroupLayout(AppPanel);
        AppPanel.setLayout(AppPanelLayout);
        AppPanelLayout.setHorizontalGroup(
            AppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(Header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AppPanelLayout.setVerticalGroup(
            AppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppPanelLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel))
        );

        File_Menu.setText("File");
        App_MenuBar.add(File_Menu);

        View_Menu.setText("View");

        Theme_Menu_Item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Theme_Menu_Item.setText("Themes");
        Theme_Menu_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Theme_Menu_ItemActionPerformed(evt);
            }
        });
        View_Menu.add(Theme_Menu_Item);

        App_MenuBar.add(View_Menu);

        setJMenuBar(App_MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Theme_Menu_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Theme_Menu_ItemActionPerformed
        // TODO add your handling code here:
        new ThemeMangerUI();
    }//GEN-LAST:event_Theme_Menu_ItemActionPerformed

    private void Book_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_btnActionPerformed
        // TODO add your handling code here:
        switchToBookPanel();
    }//GEN-LAST:event_Book_btnActionPerformed

    private void Profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_btnActionPerformed
        // TODO add your handling code here:
        switchToProfilePanel();
    }//GEN-LAST:event_Profile_btnActionPerformed

    private void switchToBookPanel(){
        SelectedBook = null;
        Profile_Panel.setVisible(false);
        Book_Panel.setVisible(true);
    }

    private void switchToProfilePanel(){
        SelectedBook = null;
        Profile_Panel.setVisible(true);
        Book_Panel.setVisible(false);
    }

    private void Logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btnActionPerformed
        // TODO add your handling code here:
        MainApp.logout();
        this.dispose();
    }//GEN-LAST:event_Logout_btnActionPerformed

    private void Book_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_TableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) Book_Table.getModel();
        String ISBN = tb.getValueAt(Book_Table.getSelectedRow(), 0).toString();
        SelectedBook = MainApp.getBook(ISBN);
        refreshBookFields();
        Book_ISBN_txt.setEditable(false);
        Book_Status_Checkbox.setEnabled(true);
    }//GEN-LAST:event_Book_TableMouseClicked

    private void Book_Save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_Save_btnActionPerformed
        // TODO add your handling code here:
        SaveAction();
    }//GEN-LAST:event_Book_Save_btnActionPerformed

    private void SaveAction(){
        if (SelectedBook == null) {
            MainApp.setStatus(0,"Please Select a Book");
            return;
        }

        String name = Book_Name_txt.getText();
        String Author = Book_Author_txt.getText();
        Boolean isAvailable = Book_Status_Checkbox.isSelected();

        MainApp.editBook(SelectedBook,name,Author,isAvailable);

        Status status = MainApp.getStatus();

        switch (status.getErrorCode()){
            case 1->{Book_ISBN_txt.requestFocus();}
            case 2->{Book_Name_txt.requestFocus();}
            case 3->{Book_Author_txt.requestFocus();}
            case 4->{Book_Status_Checkbox.requestFocus();}
        }
        if (status.getErrorCode() == -2){
            refreshBooksTable();
        }else{
            JOptionPane.showMessageDialog(null,status.getstatusMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void Book_Clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_Clear_btnActionPerformed
        // TODO add your handling code here:
        clearBookFields();
        SelectedBook = null;
        Book_ISBN_txt.setEditable(true);
        Book_Status_Checkbox.setEnabled(false);
    }//GEN-LAST:event_Book_Clear_btnActionPerformed

    private void Book_Create_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_Create_btnActionPerformed
        // TODO add your handling code here:

        String ISBN = Book_ISBN_txt.getText();
        String name = Book_Name_txt.getText();
        String Author = Book_Author_txt.getText();

        MainApp.createBook(ISBN,name,Author);
        Status status = MainApp.getStatus();

        switch (status.getErrorCode()){
            case 1->{Book_ISBN_txt.requestFocus();}
            case 2->{Book_Name_txt.requestFocus();}
            case 3->{Book_Author_txt.requestFocus();}
            case 4->{Book_Status_Checkbox.requestFocus();}
        }
        if (status.getErrorCode() == -2){
            Book_ISBN_txt.setEditable(false);
            Book_Status_Checkbox.setEnabled(true);
            clearBookFields();
        }else{
            JOptionPane.showMessageDialog(null,status.getstatusMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        refreshBooksTable();
        SelectedBook = null;
    }//GEN-LAST:event_Book_Create_btnActionPerformed


    private void Book_Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_Delete_btnActionPerformed
        // TODO add your handling code here:
        if (SelectedBook == null) {
            MainApp.setStatus(0,"Please Select a Book");
            return;
        }

        int ans = JOptionPane.showConfirmDialog(this, "Are you a Sure you want to delete " + SelectedBook.getName(),
            "confirmation", JOptionPane.YES_NO_OPTION);

        if (ans == JOptionPane.YES_OPTION) {
            MainApp.deleteBook(SelectedBook.getISBN());
            clearBookFields();
        }
        refreshBooksTable();
        SelectedBook = null;
    }//GEN-LAST:event_Book_Delete_btnActionPerformed

    private void Book_Reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_Reset_btnActionPerformed
        // TODO add your handling code here:
        if (SelectedBook == null) {
            MainApp.setStatus(0,"Please Select a Book");
            return;
        }
        refreshBooksTable();
        refreshBookFields();
    }//GEN-LAST:event_Book_Reset_btnActionPerformed

    private void Reset_Profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_Profile_btnActionPerformed
        // TODO add your handling code here:
        ReloadProfileFields();
    }//GEN-LAST:event_Reset_Profile_btnActionPerformed

    private void Delete_Acc_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_Acc_btnActionPerformed
        // TODO add your handling code here:
        int ans = JOptionPane.showConfirmDialog(this, "Are you a Sure you want to delete this account?",
            "confirmation", JOptionPane.YES_NO_OPTION);

        if (ans == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Account deleted successfully");
            MainApp.deleteAccount();
            this.dispose();
        }
    }//GEN-LAST:event_Delete_Acc_btnActionPerformed

    private void Save_Profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_Profile_btnActionPerformed
        // TODO add your handling code here:
        String name = Librarian_Name_txt.getText();
        String email = Librarian_Email_txt.getText();
        String password = Librarian_Password_txt.getText();
        String exp = Librarian_Exp_Selector.getSelectedItem().toString();

        MainApp.editLibrarian(user,name,email,password,exp);

        Status status = MainApp.getStatus();
        Status_Profile_Label.setText(status.getstatusMessage());

        switch (status.getErrorCode()){
            case 1->{Librarian_Name_txt.requestFocus();}
            case 2->{
                Librarian_Email_txt.requestFocus();
                Librarian_Email_txt.setText(user.getEmail());
            }
            case 4 ->{
                Librarian_Exp_Selector.requestFocus();
            }
        }
        ReloadProfileFields();
    }//GEN-LAST:event_Save_Profile_btnActionPerformed

    private void ReloadProfileFields(){
        Profile_btn.setText(user.getName());

        Librarian_ID_txt.setText(user.getId() + "");
        Librarian_Name_txt.setText(user.getName());

        Librarian_Email_txt.setText(user.getEmail());
        Librarian_Password_txt.setText("");
        Librarian_Exp_Selector.setSelectedIndex(Integer.parseInt(user.getExperience().substring(0,1))-1);
    }

    private void refreshBooksTable(){
        DefaultTableModel tb = (DefaultTableModel) Book_Table.getModel();
        while (tb.getRowCount() > 0) {
            tb.removeRow(tb.getRowCount()-1);
        }
        ArrayList<Book> books = MainApp.getBooks();
        for (Book book : books) {
            tb.addRow(new Object[]{book.getISBN(),book.getName(),book.getAuthor(),(book.getAvailable()?"Available":"Not Available")});
        }
    }

    private void refreshBookFields(){

        Book_ISBN_txt.setText(SelectedBook.getISBN());

        Book_Name_txt.setText(SelectedBook.getName());

        Book_Author_txt.setText(SelectedBook.getAuthor());
        Book_Status_Checkbox.setSelected(SelectedBook.getAvailable());
    }

    private void clearBookFields() {
        Book_ISBN_txt.setText("");
        Book_Name_txt.setText("");
        Book_Author_txt.setText("");
        Book_Status_Checkbox.setSelected(false);
    }

    private void Book_ISBN_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_ISBN_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book_ISBN_txtActionPerformed

    private void Book_Status_CheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_Status_CheckboxActionPerformed
        // TODO add your handling code here:
        SaveAction();
    }//GEN-LAST:event_Book_Status_CheckboxActionPerformed

    private void Librarian_Exp_SelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Librarian_Exp_SelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Librarian_Exp_SelectorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianAppUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AppPanel;
    private javax.swing.JMenuBar App_MenuBar;
    private javax.swing.JLabel Book_Author_Label;
    private javax.swing.JTextField Book_Author_txt;
    private javax.swing.JButton Book_Clear_btn;
    private javax.swing.JButton Book_Create_btn;
    private javax.swing.JButton Book_Delete_btn;
    private javax.swing.JLabel Book_ISBN_Label;
    private javax.swing.JTextField Book_ISBN_txt;
    private javax.swing.JPanel Book_Info_Tab;
    private javax.swing.JLabel Book_Name_Label;
    private javax.swing.JTextField Book_Name_txt;
    private javax.swing.JPanel Book_Panel;
    private javax.swing.JButton Book_Reset_btn;
    private javax.swing.JButton Book_Save_btn;
    private javax.swing.JCheckBox Book_Status_Checkbox;
    private javax.swing.JTabbedPane Book_Tabbed_Panel;
    private javax.swing.JTable Book_Table;
    private javax.swing.JScrollPane Book_Table_Scroll;
    private javax.swing.JButton Book_btn;
    private javax.swing.JButton Delete_Acc_btn;
    private javax.swing.JMenu File_Menu;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Librarian_Email_Label;
    private javax.swing.JTextField Librarian_Email_txt;
    private javax.swing.JLabel Librarian_Exp_Label;
    private javax.swing.JComboBox<String> Librarian_Exp_Selector;
    private javax.swing.JLabel Librarian_ID_Label;
    private javax.swing.JTextField Librarian_ID_txt;
    private javax.swing.JLabel Librarian_Name_Label;
    private javax.swing.JTextField Librarian_Name_txt;
    private javax.swing.JLabel Librarian_Password_Label;
    private javax.swing.JPasswordField Librarian_Password_txt;
    private javax.swing.JButton Logout_btn;
    private javax.swing.JLayeredPane MainPanel;
    private javax.swing.JLabel Profile_Label;
    private javax.swing.JPanel Profile_Panel;
    private javax.swing.JButton Profile_btn;
    private javax.swing.JButton Reset_Profile_btn;
    private javax.swing.JButton Save_Profile_btn;
    private javax.swing.JLabel Status_Profile_Label;
    private javax.swing.JMenuItem Theme_Menu_Item;
    private javax.swing.JMenu View_Menu;
    // End of variables declaration//GEN-END:variables
}
