/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.School_app.MainApp;

import com.mycompany.School_app.AuthSystem.AuthManager;
import com.mycompany.School_app.AuthSystem.AuthManagerUI;
import com.mycompany.School_app.Data_Handler;
import com.mycompany.School_app.Grade;
import com.mycompany.School_app.Module;
import com.mycompany.School_app.School;
import com.mycompany.School_app.StatusSystem.Status;
import com.mycompany.School_app.ThemeManger.ThemeMangerUI;
import com.mycompany.School_app.User.Student;
import com.mycompany.School_app.User.User;
import com.sun.tools.javac.Main;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;

import static com.mycompany.School_app.ThemeManger.ThemeManager.getFlatLafThemes;

/**
 *
 * @author mohamed waleed
 */
public class StudentAppUI extends javax.swing.JFrame {
    private Student user;
    /**
     * Creates new form StudentAppUI
     */
    public StudentAppUI() {
        initComponents();
    }

    public StudentAppUI(Student user) {
        initComponents();
        custominit(user);
    }
    
    public void custominit(Student user){
        setLocationRelativeTo(null);
        setVisible(true);
        this.user = user;
        ReloadProfileFields();
        refreshGradesTable();
        refreshModulesTable();
        refreshEnrollmentsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AppPanel = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Profile_btn = new javax.swing.JButton();
        Logout_btn = new javax.swing.JButton();
        Grades_btn = new javax.swing.JButton();
        Enrollment_btn = new javax.swing.JButton();
        MainPanel = new javax.swing.JLayeredPane();
        Grades_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Enrollment_Panel = new javax.swing.JPanel();
        Modules_Label = new javax.swing.JLabel();
        Enrollment_Label = new javax.swing.JLabel();
        Modules_Scroll = new javax.swing.JScrollPane();
        Modules_List = new javax.swing.JList<>();
        EnrolledModules_Scroll = new javax.swing.JScrollPane();
        EnrolledModules_List = new javax.swing.JList<>();
        Enroll_Btn = new javax.swing.JButton();
        Cancel_Enrollment_btn = new javax.swing.JButton();
        Profile_Panel = new javax.swing.JPanel();
        Profile_Label = new javax.swing.JLabel();
        Reset_btn = new javax.swing.JButton();
        Delete_Acc_btn = new javax.swing.JButton();
        Student_ID_Label = new javax.swing.JLabel();
        Student_ID_txt = new javax.swing.JTextField();
        Student_Section_Label = new javax.swing.JLabel();
        Student_Section_txt = new javax.swing.JTextField();
        Student_Name_Label = new javax.swing.JLabel();
        Student_Name_txt = new javax.swing.JTextField();
        Student_ParentName_Label = new javax.swing.JLabel();
        Student_ParentName_txt = new javax.swing.JTextField();
        Student_Email_Label = new javax.swing.JLabel();
        Student_Email_txt = new javax.swing.JTextField();
        Student_Password_Label = new javax.swing.JLabel();
        Student_Password_txt = new javax.swing.JPasswordField();
        Student_MobileNo_Label = new javax.swing.JLabel();
        Student_MobileNo_txt = new javax.swing.JTextField();
        Student_Address_Label = new javax.swing.JLabel();
        Student_Address_txt = new javax.swing.JTextField();
        Student_DOB_Label = new javax.swing.JLabel();
        Student_DOB_txt = new com.toedter.calendar.JDateChooser();
        Student_Gender_Label = new javax.swing.JLabel();
        Student_Gender_Selector = new javax.swing.JComboBox<>();
        Status_Profile_Label = new javax.swing.JLabel();
        Save_btn = new javax.swing.JButton();
        App_MenuBar = new javax.swing.JMenuBar();
        File_Menu = new javax.swing.JMenu();
        View_Menu = new javax.swing.JMenu();
        Theme_Menu_Item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("School.app(Student)");

        Header.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Profile_btn.setText("Mohamed Waleed");
        Profile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_btnActionPerformed(evt);
            }
        });

        Logout_btn.setText("Logout");
        Logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_btnActionPerformed(evt);
            }
        });

        Grades_btn.setText("Grades");
        Grades_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grades_btnActionPerformed(evt);
            }
        });

        Enrollment_btn.setText("Enrollment");
        Enrollment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enrollment_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Grades_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Enrollment_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Profile_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Logout_btn)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Profile_btn)
                    .addComponent(Logout_btn)
                    .addComponent(Grades_btn)
                    .addComponent(Enrollment_btn))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        MainPanel.setLayout(new java.awt.CardLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Module code", "Module Name", "Mark", "Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout Grades_PanelLayout = new javax.swing.GroupLayout(Grades_Panel);
        Grades_Panel.setLayout(Grades_PanelLayout);
        Grades_PanelLayout.setHorizontalGroup(
            Grades_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Grades_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
                .addContainerGap())
        );
        Grades_PanelLayout.setVerticalGroup(
            Grades_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Grades_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainPanel.add(Grades_Panel, "card2");

        Enrollment_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Modules_Label.setText("Modules");

        Enrollment_Label.setText("Enrollments");

        Modules_List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Modules_Scroll.setViewportView(Modules_List);

        EnrolledModules_Scroll.setViewportView(EnrolledModules_List);

        Enroll_Btn.setText("Enroll");
        Enroll_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enroll_BtnActionPerformed(evt);
            }
        });

        Cancel_Enrollment_btn.setText("Cancel");
        Cancel_Enrollment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_Enrollment_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Enrollment_PanelLayout = new javax.swing.GroupLayout(Enrollment_Panel);
        Enrollment_Panel.setLayout(Enrollment_PanelLayout);
        Enrollment_PanelLayout.setHorizontalGroup(
            Enrollment_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Enrollment_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Enrollment_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Enrollment_PanelLayout.createSequentialGroup()
                        .addComponent(Modules_Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(Enrollment_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Enroll_Btn)
                            .addComponent(Cancel_Enrollment_btn)))
                    .addComponent(Modules_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 406, Short.MAX_VALUE)
                .addGroup(Enrollment_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnrolledModules_Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Enrollment_Label))
                .addContainerGap())
        );
        Enrollment_PanelLayout.setVerticalGroup(
            Enrollment_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Enrollment_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Enrollment_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Enrollment_PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Cancel_Enrollment_btn)
                        .addGap(18, 18, 18)
                        .addComponent(Enroll_Btn))
                    .addGroup(Enrollment_PanelLayout.createSequentialGroup()
                        .addGroup(Enrollment_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Modules_Label)
                            .addComponent(Enrollment_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Enrollment_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Modules_Scroll)
                            .addComponent(EnrolledModules_Scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))))
                .addContainerGap())
        );

        MainPanel.add(Enrollment_Panel, "card3");

        Profile_Label.setText("Profile");

        Reset_btn.setText("Reset");
        Reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_btnActionPerformed(evt);
            }
        });

        Delete_Acc_btn.setText("Delete Account");
        Delete_Acc_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_Acc_btnActionPerformed(evt);
            }
        });

        Student_ID_Label.setText("ID:");

        Student_ID_txt.setEditable(false);

        Student_Section_Label.setText("Section:");

        Student_Section_txt.setEditable(false);
        Student_Section_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Student_Section_txtKeyTyped(evt);
            }
        });

        Student_Name_Label.setText("Name:");

        Student_ParentName_Label.setText("Parent Name:");

        Student_Email_Label.setText("Email:");

        Student_Password_Label.setText("Password:");

        Student_MobileNo_Label.setText("Phone Number:");

        Student_MobileNo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Student_MobileNo_txtKeyTyped(evt);
            }
        });

        Student_Address_Label.setText("Address:");

        Student_DOB_Label.setText("Date Of Birth:");

        Student_Gender_Label.setText("Gender:");

        Student_Gender_Selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        Status_Profile_Label.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        Save_btn.setText("Save");
        Save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Profile_PanelLayout = new javax.swing.GroupLayout(Profile_Panel);
        Profile_Panel.setLayout(Profile_PanelLayout);
        Profile_PanelLayout.setHorizontalGroup(
            Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Profile_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Profile_PanelLayout.createSequentialGroup()
                        .addComponent(Student_Email_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Student_Email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Student_Password_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Student_Password_txt))
                    .addGroup(Profile_PanelLayout.createSequentialGroup()
                        .addComponent(Status_Profile_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Save_btn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Profile_PanelLayout.createSequentialGroup()
                        .addComponent(Profile_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Reset_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delete_Acc_btn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Profile_PanelLayout.createSequentialGroup()
                        .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Profile_PanelLayout.createSequentialGroup()
                                .addComponent(Student_DOB_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Student_DOB_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Profile_PanelLayout.createSequentialGroup()
                                .addComponent(Student_MobileNo_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Student_MobileNo_txt)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Student_Gender_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Student_Address_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Profile_PanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(Student_Gender_Selector, 0, 607, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Profile_PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Student_Address_txt))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Profile_PanelLayout.createSequentialGroup()
                        .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Profile_PanelLayout.createSequentialGroup()
                                .addComponent(Student_ID_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Student_ID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Student_Section_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Profile_PanelLayout.createSequentialGroup()
                                .addComponent(Student_Name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(Student_Name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Student_ParentName_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Student_ParentName_txt)
                            .addComponent(Student_Section_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE))))
                .addContainerGap())
        );
        Profile_PanelLayout.setVerticalGroup(
            Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Profile_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Profile_Label)
                    .addComponent(Delete_Acc_btn)
                    .addComponent(Reset_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Student_ID_Label)
                    .addComponent(Student_ID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Student_Section_Label)
                    .addComponent(Student_Section_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Student_Name_Label)
                    .addComponent(Student_ParentName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Student_ParentName_Label)
                    .addComponent(Student_Name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Student_Email_Label)
                    .addComponent(Student_Email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Student_Password_Label)
                    .addComponent(Student_Password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Student_MobileNo_Label)
                    .addComponent(Student_MobileNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Student_Address_Label)
                    .addComponent(Student_Address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Student_Gender_Selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Student_Gender_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Student_DOB_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Student_DOB_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Status_Profile_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Save_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        MainPanel.add(Profile_Panel, "card4");

        javax.swing.GroupLayout AppPanelLayout = new javax.swing.GroupLayout(AppPanel);
        AppPanel.setLayout(AppPanelLayout);
        AppPanelLayout.setHorizontalGroup(
            AppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        AppPanelLayout.setVerticalGroup(
            AppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppPanelLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel))
        );

        File_Menu.setText("File");
        App_MenuBar.add(File_Menu);

        View_Menu.setText("View");

        Theme_Menu_Item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Theme_Menu_Item.setText("Themes");
        Theme_Menu_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Theme_Menu_ItemActionPerformed(evt);
            }
        });
        View_Menu.add(Theme_Menu_Item);

        App_MenuBar.add(View_Menu);

        setJMenuBar(App_MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Theme_Menu_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Theme_Menu_ItemActionPerformed
        // TODO add your handling code here:
        new ThemeMangerUI();
    }//GEN-LAST:event_Theme_Menu_ItemActionPerformed

    private void Profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_btnActionPerformed
        // TODO add your handling code here:
        Profile_Panel.setVisible(true);
        Enrollment_Panel.setVisible(false);
        Grades_Panel.setVisible(false);
    }//GEN-LAST:event_Profile_btnActionPerformed

    private void Logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btnActionPerformed
        // TODO add your handling code here:
        MainApp.logout();
        this.dispose();
    }//GEN-LAST:event_Logout_btnActionPerformed

    private void Grades_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grades_btnActionPerformed
        // TODO add your handling code here:
        Profile_Panel.setVisible(false);
        Enrollment_Panel.setVisible(false);
        Grades_Panel.setVisible(true);
    }//GEN-LAST:event_Grades_btnActionPerformed

    private void Enrollment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enrollment_btnActionPerformed
        // TODO add your handling code here:
        Profile_Panel.setVisible(false);
        Enrollment_Panel.setVisible(true);
        Grades_Panel.setVisible(false);
    }//GEN-LAST:event_Enrollment_btnActionPerformed

    private void Student_Section_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Student_Section_txtKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isLetter(c)) {
            evt.consume();
        }
        if (Student_Section_txt.getText().length() >= 1) {
            evt.consume(); // ignore extra input
        }
    }//GEN-LAST:event_Student_Section_txtKeyTyped

    private void Student_MobileNo_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Student_MobileNo_txtKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Student_MobileNo_txtKeyTyped

    private void Save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_btnActionPerformed
        // TODO add your handling code here:
        String section = Student_Section_txt.getText();

        String name = Student_Name_txt.getText();
        String parentName = Student_ParentName_txt.getText();

        String email = Student_Email_txt.getText();
        String password = Student_Password_txt.getText();

        String mobileNo = Student_MobileNo_txt.getText();
        String address = Student_Address_txt.getText();

        Date DOB = Student_DOB_txt.getDate();
        String gender = Student_Gender_Selector.getSelectedItem().toString();

        MainApp.editStudent(user,section,name,parentName,email,password,mobileNo,address,DOB,gender);

        Status status = MainApp.getStatus();
        Status_Profile_Label.setText(status.getstatusMessage());

        switch (status.getErrorCode()){
            case 1->{Student_Section_txt.requestFocus();}
            case 2->{Student_Name_txt.requestFocus();}
            case 3->{Student_ParentName_txt.requestFocus();}
            case 4->{
                Student_Email_txt.requestFocus();
                Student_Email_txt.setText(user.getEmail());
            }
            case 5->{Student_Password_txt.requestFocus();}
            case 6->{Student_MobileNo_txt.requestFocus();}
            case 7->{Student_Address_txt.requestFocus();}
            case 8->{Student_DOB_txt.requestFocus();}
        }

        ReloadProfileFields();
    }//GEN-LAST:event_Save_btnActionPerformed

    private void Enroll_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enroll_BtnActionPerformed
        // TODO add your handling code here:
        int moduleIndex = Modules_List.getSelectedIndex();
        if (moduleIndex >= 0) {
            MainApp.addModule(user,moduleIndex);
        }
        refreshModulesTable();
        refreshEnrollmentsTable();
    }//GEN-LAST:event_Enroll_BtnActionPerformed

    private void Cancel_Enrollment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_Enrollment_btnActionPerformed
        // TODO add your handling code here:
        if (EnrolledModules_List.getSelectedIndex() >= 0) {
            String modulename = EnrolledModules_List.getSelectedValue().toString();
            if (!modulename.isEmpty()) {
                MainApp.cancelModule(user,modulename);
            }
            refreshModulesTable();
            refreshEnrollmentsTable();
        }
    }//GEN-LAST:event_Cancel_Enrollment_btnActionPerformed

    private void Reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_btnActionPerformed
        // TODO add your handling code here:
        ReloadProfileFields();
    }//GEN-LAST:event_Reset_btnActionPerformed

    private void Delete_Acc_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_Acc_btnActionPerformed
        // TODO add your handling code here:
        int ans = JOptionPane.showConfirmDialog(this, "Are you a Sure you want to delete this account?",
                "confirmation", JOptionPane.YES_NO_OPTION);

        if (ans == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Account deleted successfully");
            MainApp.deleteAccount();
            this.dispose();
        }
    }//GEN-LAST:event_Delete_Acc_btnActionPerformed


    private void ReloadProfileFields(){
        Profile_btn.setText(user.getName());

        Student_ID_txt.setText(user.getId() + "");
        Student_Section_txt.setText(user.getSection());

        Student_ParentName_txt.setText(user.getParentName());
        Student_Name_txt.setText(user.getName());

        Student_Email_txt.setText(user.getEmail());
        Student_Password_txt.setText("");

        Student_MobileNo_txt.setText(user.getMobileNo());
        Student_Address_txt.setText(user.getAddress());

        Student_DOB_txt.setDate(user.getDOB());
        Student_Gender_Selector.setSelectedItem(user.getGender());
    }

    private void refreshGradesTable(){
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();

        while (tb.getRowCount() > 0) {
            tb.removeRow(tb.getRowCount()-1);
        }

        ArrayList<Grade> grades = MainApp.getStudentGrades(user);
        grades.stream()
                .forEach(grade ->
                        tb.addRow(new Object[]{grade.getModule().getId(),grade.getModule().getName(),grade.getGrade(),grade.getGradeChar()})
                );
    }

    private void refreshModulesTable(){
        ArrayList<Module> modules = MainApp.getCompatibleModules(user);
        Modules_List.setModel(new AbstractListModel<String>() {
            String[] strings = modules.stream().map(Module::getName).toArray(String[]::new);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
    }

    private void refreshEnrollmentsTable(){
        HashSet<Module> modules = MainApp.getStudentModules(user);
        if (modules != null) {
            EnrolledModules_List.setModel(new AbstractListModel<String>() {
                String[] strings = modules.stream().map(Module::getName).toArray(String[]::new);
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentAppUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AppPanel;
    private javax.swing.JMenuBar App_MenuBar;
    private javax.swing.JButton Cancel_Enrollment_btn;
    private javax.swing.JButton Delete_Acc_btn;
    private javax.swing.JButton Enroll_Btn;
    private javax.swing.JList<String> EnrolledModules_List;
    private javax.swing.JScrollPane EnrolledModules_Scroll;
    private javax.swing.JLabel Enrollment_Label;
    private javax.swing.JPanel Enrollment_Panel;
    private javax.swing.JButton Enrollment_btn;
    private javax.swing.JMenu File_Menu;
    private javax.swing.JPanel Grades_Panel;
    private javax.swing.JButton Grades_btn;
    private javax.swing.JPanel Header;
    private javax.swing.JButton Logout_btn;
    private javax.swing.JLayeredPane MainPanel;
    private javax.swing.JLabel Modules_Label;
    private javax.swing.JList<String> Modules_List;
    private javax.swing.JScrollPane Modules_Scroll;
    private javax.swing.JLabel Profile_Label;
    private javax.swing.JPanel Profile_Panel;
    private javax.swing.JButton Profile_btn;
    private javax.swing.JButton Reset_btn;
    private javax.swing.JButton Save_btn;
    private javax.swing.JLabel Status_Profile_Label;
    private javax.swing.JLabel Student_Address_Label;
    private javax.swing.JTextField Student_Address_txt;
    private javax.swing.JLabel Student_DOB_Label;
    private com.toedter.calendar.JDateChooser Student_DOB_txt;
    private javax.swing.JLabel Student_Email_Label;
    private javax.swing.JTextField Student_Email_txt;
    private javax.swing.JLabel Student_Gender_Label;
    private javax.swing.JComboBox<String> Student_Gender_Selector;
    private javax.swing.JLabel Student_ID_Label;
    private javax.swing.JTextField Student_ID_txt;
    private javax.swing.JLabel Student_MobileNo_Label;
    private javax.swing.JTextField Student_MobileNo_txt;
    private javax.swing.JLabel Student_Name_Label;
    private javax.swing.JTextField Student_Name_txt;
    private javax.swing.JLabel Student_ParentName_Label;
    private javax.swing.JTextField Student_ParentName_txt;
    private javax.swing.JLabel Student_Password_Label;
    private javax.swing.JPasswordField Student_Password_txt;
    private javax.swing.JLabel Student_Section_Label;
    private javax.swing.JTextField Student_Section_txt;
    private javax.swing.JMenuItem Theme_Menu_Item;
    private javax.swing.JMenu View_Menu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
